# Import everything from the sub-files
from .auth import UserLogin, TokenResponse, UserSignUp
from .student import (StudentLessons, 
                      WeeklyLesson, 
                      TodaysLessons, 
                      OverallLessonsResponse, 
                      EmergencyContactSchema, 
                      AttendancePerModule,
                      PreviousAttendances,
                      WeeklyLesson,
                      ModuleProgress,
                      StudentProgressResponse,
                      AttendanceLogItem,
                      StudentProfileDetails,
                      NotificationItem
                      )
from .lecturer import( timetableEntry, 
                        AttendanceOverviewCard, 
                        RecentSessionsCardData, 
                        RecentSessionRecord, 
                        courseoverviewcard, 
                        ClassToday,
                        Literal,
                        viewUserProfile,
                        UserProfileUpdate,
                        ReportCriteria,
                        AttendanceLogEntry,
                        DetailedAttendanceRecord,
                        DailyTimetable,
                        Weeklytimetable,
                        MonthlyTimetable,
                        AttendanceDetailRow,
                        OverallClassAttendanceDetails,
                        ReportHistoryEntry)
from .admin import (AdminDashboardStats, 
                    CourseAttentionItem, 
                    UserManagementItem)
from .platformManager import (PlatformManagerDashboard, 
                              DashboardStats, 
                              UniversityDisplay, 
                              InstitutionProfile,
                              InstitutionCreate,
                              PaginatedInstitutionResponse)