"""Added 'generated_report' table

Revision ID: 0c349db0d23f
Revises: f9885b4e5bc9
Create Date: 2026-01-08 13:18:12.813848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c349db0d23f'
down_revision: Union[str, Sequence[str], None] = 'f9885b4e5bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_reports',
    sa.Column('reportID', sa.Integer(), nullable=False),
    sa.Column('lecturerID', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('moduleCode', sa.String(length=20), nullable=False),
    sa.Column('reportType', sa.String(length=50), nullable=False),
    sa.Column('filterStatus', sa.String(length=50), nullable=False),
    sa.Column('generatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fileName', sa.String(length=255), nullable=False),
    sa.Column('filePath', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['lecturerID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('reportID')
    )
    op.drop_column('attdcheck', 'remarks')
    op.drop_column('users', 'creationDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('creationDate', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('attdcheck', sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('generated_reports')
    # ### end Alembic commands ###
