"""EntLeave_AttdCheck changes

Revision ID: 0ec18bb68a50
Revises: f83ffbbc7232
Create Date: 2026-02-01 16:20:50.640790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ec18bb68a50'
down_revision: Union[str, Sequence[str], None] = 'f83ffbbc7232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attdcheck', sa.Column('firstDetection', sa.DateTime(), nullable=True))
    op.add_column('attdcheck', sa.Column('lastDetection', sa.DateTime(), nullable=True))
    op.alter_column('courses', 'courseCode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.add_column('entleave', sa.Column('detectionTime', sa.DateTime(), nullable=False))
    op.drop_column('entleave', 'enter')
    op.drop_column('entleave', 'leave')
    op.alter_column('modules', 'moduleName',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.alter_column('modules', 'moduleCode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'moduleCode',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('modules', 'moduleName',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('entleave', sa.Column('leave', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('entleave', sa.Column('enter', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('entleave', 'detectionTime')
    op.alter_column('courses', 'courseCode',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('attdcheck', 'lastDetection')
    op.drop_column('attdcheck', 'firstDetection')
    # ### end Alembic commands ###
