"""studentimage_updatedAt

Revision ID: 1b955c66d49b
Revises: c342b4ed0910
Create Date: 2026-02-10 23:19:11.420796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b955c66d49b'
down_revision: Union[str, Sequence[str], None] = 'c342b4ed0910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentangles', sa.Column('imagepath', sa.String(), nullable=False))
    op.add_column('studentangles', sa.Column('updatedat', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentangles', 'updatedat')
    op.drop_column('studentangles', 'imagepath')
    # ### end Alembic commands ###
