"""lessonLocal

Revision ID: 21b85fe16640
Revises: 63d1cdf2e9c4
Create Date: 2025-12-13 15:11:51.949031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b85fe16640'
down_revision: Union[str, Sequence[str], None] = '63d1cdf2e9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('building', sa.String(length=4), nullable=False))
    op.add_column('lessons', sa.Column('room', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'room')
    op.drop_column('lessons', 'building')
    # ### end Alembic commands ###
