"""studentNumberandOtherUserRoles

Revision ID: 2917a4f5c7a8
Revises: 31573afc0c57
Create Date: 2025-12-11 16:26:54.868754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2917a4f5c7a8'
down_revision: Union[str, Sequence[str], None] = '31573afc0c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('role', sa.String(), nullable=False))
    op.add_column('lecturers', sa.Column('specialistIn', sa.String(), nullable=False))
    op.add_column('students', sa.Column('studentNum', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'studentNum')
    op.drop_column('lecturers', 'specialistIn')
    op.drop_column('admins', 'role')
    # ### end Alembic commands ###
