"""Add 'isactive' to 'University' table

Revision ID: 2dc7bfe89d6b
Revises: a1205e3c5ed7
Create Date: 2025-12-30 19:33:23.739593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc7bfe89d6b'
down_revision: Union[str, Sequence[str], None] = 'a1205e3c5ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
