"""Add 'isActive' to 'University' table

Revision ID: 3164852bf16a
Revises: 2dc7bfe89d6b
Create Date: 2025-12-30 19:40:33.156345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3164852bf16a'
down_revision: Union[str, Sequence[str], None] = '2dc7bfe89d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('isActive', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'isActive')
    # ### end Alembic commands ###
