"""studentangles

Revision ID: 6332edb4a8d0
Revises: b488a4911914
Create Date: 2025-12-09 14:27:40.334208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6332edb4a8d0'
down_revision: Union[str, Sequence[str], None] = 'b488a4911914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentphotos',
    sa.Column('studentID', sa.UUID(), nullable=False),
    sa.Column('photoAngle', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('studentID', 'photoAngle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentphotos')
    # ### end Alembic commands ###
