"""studentNumberandOtherUserRoles2

Revision ID: 63d1cdf2e9c4
Revises: 2917a4f5c7a8
Create Date: 2025-12-11 16:48:17.444589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d1cdf2e9c4'
down_revision: Union[str, Sequence[str], None] = '2917a4f5c7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentphotos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentphotos',
    sa.Column('studentID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('photoAngle', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], name=op.f('studentphotos_studentID_fkey')),
    sa.PrimaryKeyConstraint('studentID', 'photoAngle', name=op.f('studentphotos_pkey'))
    )
    # ### end Alembic commands ###
