"""modules_campuses

Revision ID: 7f6045268036
Revises: 1b955c66d49b
Create Date: 2026-02-12 00:52:15.344020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6045268036'
down_revision: Union[str, Sequence[str], None] = '1b955c66d49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP POLICY IF EXISTS "Angle Access" ON studentangles;')
    op.add_column('modules', sa.Column('campusID', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_modules_campusID_campus'), 'modules', 'campus', ['campusID'], ['campusID'])
    op.add_column('studentangles', sa.Column('studentID', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('fk_studentangles_studentID_students'), 'studentangles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_studentangles_studentID_students'), 'studentangles', 'students', ['studentID'], ['studentID'])
    op.drop_column('studentangles', 'studentid')
    op.execute("""
        CREATE POLICY "Angle Access" ON studentangles
        FOR ALL TO authenticated
        USING (auth.uid() = "studentID");
    """)
    op.execute("""
        CREATE POLICY "Campus Data Isolation" ON modules
        FOR ALL TO authenticated
        USING (
            EXISTS (
                SELECT 1 FROM admins WHERE admins."adminID" = auth.uid() AND admins."campusID" = modules."campusID"
            ) OR
            EXISTS (
                SELECT 1 FROM lecturers WHERE lecturers."lecturerID" = auth.uid() AND lecturers."campusID" = modules."campusID"
            ) OR
            EXISTS (
                SELECT 1 FROM students WHERE students."studentID" = auth.uid() AND students."campusID" = modules."campusID"
            )
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP POLICY IF EXISTS "Campus Data Isolation" ON modules;')
    op.execute('DROP POLICY IF EXISTS "Angle Access" ON studentangles;')
    op.add_column('studentangles', sa.Column('studentid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_studentangles_studentID_students'), 'studentangles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_studentangles_studentID_students'), 'studentangles', 'students', ['studentid'], ['studentID'])
    op.drop_column('studentangles', 'studentID')
    op.drop_constraint(op.f('fk_modules_campusID_campus'), 'modules', type_='foreignkey')
    op.drop_column('modules', 'campusID')
    op.execute('CREATE POLICY "Angle Access" ON studentangles FOR ALL USING (auth.uid() = studentid);')
    # ### end Alembic commands ###
