"""notif_tbl

Revision ID: 80913880056e
Revises: ed2562d99b28
Create Date: 2026-01-27 13:31:24.951634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80913880056e'
down_revision: Union[str, Sequence[str], None] = 'ed2562d99b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentnotifications',
    sa.Column('notificationID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=False),
    sa.Column('generatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('notificationID')
    )
    op.execute("ALTER TABLE studentnotifications ENABLE ROW LEVEL SECURITY")

    op.execute("""
        CREATE POLICY "Students see own notifications"
        ON studentnotifications
        FOR SELECT
        USING (auth.uid() = "studentID");
    """)

    op.execute("""
        CREATE POLICY "Students update own notifications"
        ON studentnotifications
        FOR UPDATE
        USING (auth.uid() = "studentID")
        WITH CHECK (auth.uid() = "studentID");
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentnotifications')
    # ### end Alembic commands ###
