"""additionalUserDetails

Revision ID: 883770917fae
Revises: 21b85fe16640
Create Date: 2025-12-15 17:54:30.705088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883770917fae'
down_revision: Union[str, Sequence[str], None] = '21b85fe16640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'building',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('lessons', 'room',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=50),
               nullable=True)
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('fulladdress', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('eName', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('eRole', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('ePhone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ePhone')
    op.drop_column('users', 'eRole')
    op.drop_column('users', 'eName')
    op.drop_column('users', 'fulladdress')
    op.drop_column('users', 'phone')
    op.alter_column('lessons', 'room',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('lessons', 'building',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###
