"""Add 'subscriptionDate' to 'University' table

Revision ID: a1205e3c5ed7
Revises: ead044b5e903
Create Date: 2025-12-30 14:04:36.392227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1205e3c5ed7'
down_revision: Union[str, Sequence[str], None] = 'ead044b5e903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('subscriptionDate', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'subscriptionDate')
    # ### end Alembic commands ###
