"""second revision 111120250317

Revision ID: a41c396c5f0a
Revises: c6e7627e71f7
Create Date: 2025-11-11 03:20:25.652947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a41c396c5f0a'
down_revision: Union[str, Sequence[str], None] = 'c6e7627e71f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Courses',
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('courseCode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('courseID')
    )
    op.create_table('AttdCheck',
    sa.Column('AttdCheckID', sa.Integer(), nullable=False),
    sa.Column('lessonID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('attendance_check', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lessonID'], ['Lessons.lessonID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['Students.studentID'], ),
    sa.PrimaryKeyConstraint('AttdCheckID')
    )
    op.create_table('EntLeave',
    sa.Column('entLeaveID', sa.Integer(), nullable=False),
    sa.Column('lessonID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('enter', sa.DateTime(), nullable=False),
    sa.Column('leave', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lessonID'], ['Lessons.lessonID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['Students.studentID'], ),
    sa.PrimaryKeyConstraint('entLeaveID')
    )
    op.drop_table('Attendance')
    op.drop_constraint(op.f('Lessons_studentsID_fkey'), 'Lessons', type_='foreignkey')
    op.drop_column('Lessons', 'studentsID')
    op.add_column('Students', sa.Column('courseID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Students', 'Courses', ['courseID'], ['courseID'])
    op.drop_column('Students', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Students', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Students', type_='foreignkey')
    op.drop_column('Students', 'courseID')
    op.add_column('Lessons', sa.Column('studentsID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('Lessons_studentsID_fkey'), 'Lessons', 'Students', ['studentsID'], ['studentID'])
    op.create_table('Attendance',
    sa.Column('attendanceID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lessonID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('studentID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attendance_check', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enter', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('leave', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lessonID'], ['Lessons.lessonID'], name=op.f('Attendance_lessonID_fkey')),
    sa.ForeignKeyConstraint(['studentID'], ['Students.studentID'], name=op.f('Attendance_studentID_fkey')),
    sa.PrimaryKeyConstraint('attendanceID', name=op.f('Attendance_pkey'))
    )
    op.drop_table('EntLeave')
    op.drop_table('AttdCheck')
    op.drop_table('Courses')
    # ### end Alembic commands ###
