"""studentNum

Revision ID: b2af5dbf09aa
Revises: 0ec18bb68a50
Create Date: 2026-02-03 23:22:55.736062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2af5dbf09aa'
down_revision: Union[str, Sequence[str], None] = '0ec18bb68a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'studentNum',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'studentNum',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
