"""Pass Removal

Revision ID: b488a4911914
Revises: 8e67e1ca947b
Create Date: 2025-12-08 01:16:12.091562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b488a4911914'
down_revision: Union[str, Sequence[str], None] = '8e67e1ca947b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
