"""tutorialgroup_names

Revision ID: bc6da4a655cc
Revises: 7f6045268036
Create Date: 2026-02-12 01:49:21.075805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6da4a655cc'
down_revision: Union[str, Sequence[str], None] = '7f6045268036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorialgroups', sa.Column('groupName', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutorialgroups', 'groupName')
    # ### end Alembic commands ###
