"""First Revision

Revision ID: c6e7627e71f7
Revises: 
Create Date: 2025-10-28 21:10:25.376591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e7627e71f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Modules',
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.Column('moduleName', sa.String(length=25), nullable=False),
    sa.Column('moduleCode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('moduleID')
    )
    op.create_table('UserProfiles',
    sa.Column('profileTypeID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('profileTypeID')
    )
    op.create_table('Users',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('profileTypeID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['profileTypeID'], ['UserProfiles.profileTypeID'], ),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_table('Admins',
    sa.Column('adminID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminID'], ['Users.userID'], ),
    sa.PrimaryKeyConstraint('adminID')
    )
    op.create_table('Lecturers',
    sa.Column('lecturerID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecturerID'], ['Users.userID'], ),
    sa.PrimaryKeyConstraint('lecturerID')
    )
    op.create_table('Students',
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('attendanceMinimum', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['Users.userID'], ),
    sa.PrimaryKeyConstraint('studentID')
    )
    op.create_table('LecMods',
    sa.Column('lecModID', sa.Integer(), nullable=False),
    sa.Column('lecturerID', sa.Integer(), nullable=False),
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecturerID'], ['Lecturers.lecturerID'], ),
    sa.ForeignKeyConstraint(['moduleID'], ['Modules.moduleID'], ),
    sa.PrimaryKeyConstraint('lecModID')
    )
    op.create_table('StudentLessons',
    sa.Column('studentLessonsID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('lecturerID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecturerID'], ['Lecturers.lecturerID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['Students.studentID'], ),
    sa.PrimaryKeyConstraint('studentLessonsID')
    )
    op.create_table('Studentfaces',
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['Students.studentID'], ),
    sa.PrimaryKeyConstraint('StudentID')
    )
    op.create_table('Lessons',
    sa.Column('lessonID', sa.Integer(), nullable=False),
    sa.Column('lecModID', sa.Integer(), nullable=False),
    sa.Column('studentsID', sa.Integer(), nullable=False),
    sa.Column('lessontype', sa.String(), nullable=False),
    sa.Column('startDateTime', sa.DateTime(), nullable=False),
    sa.Column('endDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lecModID'], ['LecMods.lecModID'], ),
    sa.ForeignKeyConstraint(['studentsID'], ['Students.studentID'], ),
    sa.PrimaryKeyConstraint('lessonID')
    )
    op.create_table('Attendance',
    sa.Column('attendanceID', sa.Integer(), nullable=False),
    sa.Column('lessonID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('attendance_check', sa.Boolean(), nullable=False),
    sa.Column('enter', sa.DateTime(), nullable=False),
    sa.Column('leave', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lessonID'], ['Lessons.lessonID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['Students.studentID'], ),
    sa.PrimaryKeyConstraint('attendanceID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Attendance')
    op.drop_table('Lessons')
    op.drop_table('Studentfaces')
    op.drop_table('StudentLessons')
    op.drop_table('LecMods')
    op.drop_table('Students')
    op.drop_table('Lecturers')
    op.drop_table('Admins')
    op.drop_table('Users')
    op.drop_table('UserProfiles')
    op.drop_table('Modules')
    # ### end Alembic commands ###
