"""studentangles2

Revision ID: de75794cba33
Revises: 6332edb4a8d0
Create Date: 2025-12-09 14:33:09.830767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de75794cba33'
down_revision: Union[str, Sequence[str], None] = '6332edb4a8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentangles',
    sa.Column('studentID', sa.UUID(), nullable=False),
    sa.Column('photoAngle', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('studentID', 'photoAngle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentangles')
    # ### end Alembic commands ###
