"""firstgeneration_spbase

Revision ID: e1ffdf6c5694
Revises: 
Create Date: 2025-12-07 17:36:13.718734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ffdf6c5694'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('courseCode', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('courseID')
    )
    op.create_table('modules',
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.Column('moduleName', sa.String(length=25), nullable=False),
    sa.Column('moduleCode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('moduleID')
    )
    op.create_table('userprofiles',
    sa.Column('profileTypeID', sa.Integer(), nullable=False),
    sa.Column('profileTypeName', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('profileTypeID')
    )
    op.create_table('users',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.Column('profileTypeID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profileTypeID'], ['userprofiles.profileTypeID'], ),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_table('admins',
    sa.Column('adminID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['adminID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('adminID')
    )
    op.create_table('lecturers',
    sa.Column('lecturerID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lecturerID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('lecturerID')
    )
    op.create_table('students',
    sa.Column('studentID', sa.UUID(), nullable=False),
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('attendanceMinimum', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['courseID'], ['courses.courseID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('studentID')
    )
    op.create_table('lecmods',
    sa.Column('lecModID', sa.Integer(), nullable=False),
    sa.Column('lecturerID', sa.UUID(), nullable=False),
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecturerID'], ['lecturers.lecturerID'], ),
    sa.ForeignKeyConstraint(['moduleID'], ['modules.moduleID'], ),
    sa.PrimaryKeyConstraint('lecModID')
    )
    op.create_table('studentmodules',
    sa.Column('studentModulesID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.UUID(), nullable=False),
    sa.Column('modulesID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulesID'], ['modules.moduleID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('studentModulesID')
    )
    op.create_table('lessons',
    sa.Column('lessonID', sa.Integer(), nullable=False),
    sa.Column('lecModID', sa.Integer(), nullable=False),
    sa.Column('lessontype', sa.String(length=10), nullable=False),
    sa.Column('startDateTime', sa.DateTime(), nullable=False),
    sa.Column('endDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lecModID'], ['lecmods.lecModID'], ),
    sa.PrimaryKeyConstraint('lessonID')
    )
    op.create_table('attdcheck',
    sa.Column('AttdCheckID', sa.Integer(), nullable=False),
    sa.Column('lessonID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lessonID'], ['lessons.lessonID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('AttdCheckID')
    )
    op.create_table('entleave',
    sa.Column('entLeaveID', sa.Integer(), nullable=False),
    sa.Column('lessonID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.UUID(), nullable=False),
    sa.Column('enter', sa.DateTime(), nullable=False),
    sa.Column('leave', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lessonID'], ['lessons.lessonID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('entLeaveID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entleave')
    op.drop_table('attdcheck')
    op.drop_table('lessons')
    op.drop_table('studentmodules')
    op.drop_table('lecmods')
    op.drop_table('students')
    op.drop_table('lecturers')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('userprofiles')
    op.drop_table('modules')
    op.drop_table('courses')
    # ### end Alembic commands ###
