"""profile_changes

Revision ID: f83ffbbc7232
Revises: c77e504e8abc
Create Date: 2026-01-29 13:42:04.049582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f83ffbbc7232'
down_revision: Union[str, Sequence[str], None] = 'c77e504e8abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customgoals')
    op.alter_column('studentnotifications', 'meta_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('students', 'attendanceMinimum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('userprofiles', sa.Column('campusID', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_userprofiles_campusID_campus'), 'userprofiles', 'campus', ['campusID'], ['campusID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_userprofiles_campusID_campus'), 'userprofiles', type_='foreignkey')
    op.drop_column('userprofiles', 'campusID')
    op.alter_column('students', 'attendanceMinimum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('studentnotifications', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('customgoals',
    sa.Column('goalID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goalPercentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('setBy', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('setByID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('lastUpdatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['setByID'], ['users.userID'], name=op.f('customgoals_setByID_fkey')),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], name=op.f('customgoals_userID_fkey')),
    sa.PrimaryKeyConstraint('goalID', name=op.f('customgoals_pkey'))
    )
    # ### end Alembic commands ###
