"""extra_user_details__attdcheck_remarks

Revision ID: f9885b4e5bc9
Revises: 3164852bf16a
Create Date: 2026-01-04 16:58:58.331904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9885b4e5bc9'
down_revision: Union[str, Sequence[str], None] = '3164852bf16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attdcheck', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('users', sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'creationDate')
    op.drop_column('attdcheck', 'remarks')
    # ### end Alembic commands ###
