"""module_dates

Revision ID: fdeb23e2d42a
Revises: 0c349db0d23f
Create Date: 2026-01-09 10:27:20.510345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdeb23e2d42a'
down_revision: Union[str, Sequence[str], None] = '0c349db0d23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attdcheck', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('modules', sa.Column('startDate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('modules', sa.Column('endDate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    op.drop_column('users', 'creationDate')
    op.drop_column('modules', 'endDate')
    op.drop_column('modules', 'startDate')
    op.drop_column('attdcheck', 'remarks')
    # ### end Alembic commands ###
